export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "#192041",
            color: "white",
            padding: "0",
            margin: "0",
          }}
        >
          <p>Header </p>
        </header>
        {children}
      </body>
    </html>
  );
}
